### ISSUE TITLE
high number of failed_reqs, psycopg2.OperationalError: could not connect to server

### ISSUE THREAD

**Issue by pocman** [miguelgrinberg/python-web-perf#2]
Hi, 
I tried running the benchmark on ubuntu 18.04, with Intel® Core™ i7-8850H CPU @ 2.60GHz × 12 and I have an issue with db connections.
```
NUM_CLIENTS=100
NUM_CONNECTIONS=20000
NUM_WORKERS_SYNC=12
NUM_WORKERS_ASYNC=6
NUM_DB_SESSIONS=100
DB_SLEEP=0.02
```
First run : gunicorn 20.0.4 with meinheld 1.0.2 -> gunicorn 20.0.4 ->  gunicorn 20.0.4 with gevent 20.9.0

| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb             | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|--------------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 6       | 2084.08  | 41  | 107 | 100         | 20000      | 0           | 555.75 | 130.2331392        | 16.6      | 14.3       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4 with gevent 20.9.0  | 6       | 1588.33  | 53  | 190 | 100         | 20000      | 0           | 470.05 | 156.13296640000002 | 52.9      | 45.7       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4                     | 12      | 540.34   | 120 | 348 | 12          | 20000      | 11566       | 971.2  | 232.3644416        | 32.2      | 27.8       | 14   |

Second run : gunicorn 20.0.4 with meinheld 1.0.2 -> gunicorn 20.0.4 with gevent 20.9.0 -> gunicorn 20.0.4
| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb      | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|-------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 6       | 2078.64  | 41  | 106 | 100         | 20000      | 0           | 551.05 | 130.1282816 | 16.5      | 14.3       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4 with gevent 20.9.0  | 6       | 921.52   | 87  | 389 | 100         | 20000      | 11662       | 582.59 | 157.810688  | 32.1      | 27.8       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4                     | 12      | 539.52   | 200 | 283 | 12          | 20000      | 7879        | 761.26 | 231.735296  | 45.6      | 39.5       | 14   |

For gunicorn 20.0.4, I saw a lot of failure at the beginning of the run but not at the end. 

And the exception raised inside the perf-app container.
```
[2020-11-30 15:14:39,832] ERROR in app: Exception on /test [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app_flask.py", line 10, in test
    a, b = get_row()
  File "/app/sync_db.py", line 17, in get_row
    conn = psycopg2.connect(dbname='test', user='test', password='test',
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Cannot assign requested address
        Is the server running on host "perf-dbpool" (172.21.0.4) and accepting
        TCP/IP connections on port 5432?
```

```
➜  ~ docker run --rm busybox cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
➜  ~ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by pocman** [comment]
I have the same issue when using aiopg.create_pool
```
import os
import random
import aiopg

max_n = 1000_000 - 1
delay = float(os.getenv('DB_SLEEP', '0'))

dsn = 'dbname=test user=test password=test host=perf-db port=5432'

async def get_row():
    async with aiopg.create_pool(dsn) as pool:
        async with pool.acquire() as conn:
            async with conn.cursor() as cursor:
                index = random.randint(1, max_n)
                await cursor.execute("select pg_sleep(%s); select a, b from test where a = %s", (delay, index))
                ((a, b),) = await cursor.fetchall()
    return a, b
```

| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb             | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|--------------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 6       | 1246.43  | 89  | 201 | 100         | 20000      | 10078       | 596.26 | 145.43749119999998 | 51.5      | 44.6       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4 with gevent 20.9.0  | 6       | 1175.87  | 68  | 309 | 100         | 20000      | 4444        | 557.95 | 158.9641216        | 40.3      | 34.8       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4                     | 12      | 383.44   | 253 | 344 | 12          | 20000      | 0           | 386.4  | 199.0197248        | 22.7      | 19.5       | 14   |

**Comment by pocman** [comment]
It looks related to https://dba.stackexchange.com/a/59709

**Comment by miguelgrinberg** [comment]
I'm not familiar with this error, so I cannot provide any actionable advice other than looking at logs in the pgbouncer container.

**Comment by pocman** [comment]
After looking at `netstat -ton|grep WAIT`, I saw some sockets in wait state.

I did the following changes :

in run-docker.sh
```
docker run --rm -d --name perf-app --sysctl net.ipv4.tcp_fin_timeout="15" --sysctl net.ipv4.ip_local_port_range="1024 65535" --sysctl net.ipv4.tcp_tw_reuse="1" --network container:perf-server -e PWPWORKERS=$PWPWORKERS -e DB_SLEEP=$DB_SLEEP perf-app ./serve-$test.sh
```
 in the docker-compose file
```
version: '3.1'
services:
  db:
    sysctls:
      net.ipv4.ip_local_port_range: 1024 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 15
...
  dbpool:
    sysctls:
      net.ipv4.ip_local_port_range: 1024 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 15
...
  server:
    sysctls:
      net.ipv4.ip_local_port_range: 1024 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 15
...
```

on my local machine
```
sudo vi /etc/sysctl.conf 

# Add the following to sysctl.conf:
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
net.ipv4.ip_local_port_range = 1025 65535

# Lastly apply changes
sudo /sbin/sysctl -p
```
---
Benchmark is now smooth : 

```
export NUM_CLIENTS=100
export NUM_CONNECTIONS=50000
export NUM_WORKERS_SYNC=100
export NUM_WORKERS_ASYNC=6
export NUM_DB_SESSIONS=100
export DB_SLEEP=0.02
```

| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb      | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|-------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 12      | 3028.24  | 32  | 53  | 100         | 50000      | 0           | 762.23 | 232.99358 | 620.0     | 536.0      | 14   |
| Flask 1.1.2 | gunicorn 20.0.4 with gevent 20.9.0  | 6       | 2504.95  | 36  | 100 | 100         | 50000      | 0           | 404.73 | 160.3272704 | 102.0     | 88.2       | 8    |
| Flask 1.1.2 | gunicorn 20.0.4                     | 19      | 629.77   | 164 | 197 | 19          | 50000      | 0           | 284.71 | 303.2481792 | 55.5      | 47.9       | 21   |
| Flask 1.1.2 | gunicorn 20.0.4                     | 100     | 2887.57  | 33  | 61  | 100         | 50000      | 0           | 426.42 | 1521.492164608 | 505.0     | 436.0      | 102  |

---

```
export NUM_CLIENTS=200
export NUM_CONNECTIONS=50000
export NUM_WORKERS_SYNC=120
export NUM_WORKERS_ASYNC=12
export NUM_DB_SESSIONS=200
export DB_SLEEP=0.05
```
| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb             | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|--------------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4                     | 120     | 1846.81  | 102 | 180 | 100         | 50000      | 0           | 252.9  | 1824.2873589760002 | 966.0     | 829.0      | 122  |
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 12      | 1792.48  | 109 | 139 | 100         | 50000      | 0           | 877.52 | 238.4461824        | 1030.0    | 877.0      | 14   |

After setting MAX_CONNECTIONS=200 on pg container.
| framework   | server                              | workers | reqs/sec | P50 | P99 | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb         | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|-----|-------------|------------|-------------|--------|----------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 24      | 2759.14  | 69  | 139 | 200         | 50000      | 0           | 887.69 | 446.693376     | 119.0     | 92.2       | 26   |
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 12      | 2545.57  | 77  | 138 | 200         | 50000      | 0           | 857.38 | 242.221056     | 51.2      | 39.5       | 14   |
| Flask 1.1.2 | gunicorn 20.0.4                     | 120     | 1557.57  | 117 | 244 | 120         | 50000      | 0           | 400.8  | 1821.066133504 | 124.0     | 95.8       | 122  |


---

```
export NUM_CLIENTS=400
export NUM_CONNECTIONS=100000
export NUM_WORKERS_SYNC=100
export NUM_WORKERS_ASYNC=12
export NUM_DB_SESSIONS=200
export DB_SLEEP=0.02
```

| framework   | server                              | workers | reqs/sec | P50 | P99  | db_sessions | total_reqs | failed_reqs | cpu_%  | ram_mb             | net_in_mb | net_out_mb | pids |
|-------------|-------------------------------------|---------|----------|-----|------|-------------|------------|-------------|--------|--------------------|-----------|------------|------|
| Flask 1.1.2 | gunicorn 20.0.4 with meinheld 1.0.2 | 12      | 4009.6   | 98  | 136  | 200         | 100000     | 0           | 675.96 | 255.64282880000002 | 98.2      | 82.9       | 14   |
| Flask 1.1.2 | gunicorn 20.0.4                     | 100     | 1839.86  | 76  | 1088 | 100         | 100000     | 19          | 426.84 | 1525.787131904     | 229.0     | 195.0      | 102  |

after setting MAX_CLIENT_CONN: 5000 on dbpool, no major improvement was detected.
